exclude: [
  "Gemfile",
  "Gemfile.lock",
  "Rakefile",
  "lib",
  "tasks",
  "spec",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "*.rb"
]

# Default frontmatter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ''
      type: 'software'
    values:
      layout: 'software'

# Setup Jekyll Collections to organize site content
collections:
  # The 'software' collection is general documentation about software produced
  # by the Samvera community.
  software:
    output: true
    layout: "software"

  posts:
    output: true
    permalink: /blog/:categories/:title

collections_dir: site_content

publish:
  git_remote: git@github.com:samvera-labs/samvera_docs.git
  git_branch: gh-pages

plugins:
  - jekyll-menus
  # - jekyll-ship

sass:
  sass_dir: _sass
