# Default frontmatter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ''
      type: 'software'
    values:
      layout: 'software'

# Setup Jekyll Collections to organize site content
collections:
  # The 'software' collection is general documentation about software produced
  # by the Samvera community.
  software:
    output: true
    layout: "software"
    permalink: :path

  posts:
    output: true
    permalink: /blog/:categories/:title

  pages:
    output: true

collections_dir: site_content

sass:
  sass_dir: _sass
